name: Run Benchmark

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_call:

jobs:
  Benchmark-LBFGS:
    strategy:
      fail-fast: false
      matrix:
        split: [1, 2, 3, 4]

    runs-on: windows-latest

    if: >
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'run CUTEst benchmark')

    env:
      MUMPS_SEQ: true
      CUTEST_SPLIT: ${{ matrix.split }}

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'

      - name: Use Julia cache
        uses: julia-actions/cache@v2

      - name: Instantiate project
        run: |
          julia --project=benchmark -e '
            using Pkg
            Pkg.instantiate()
            mkpath("benchmark/result")
          '

      - name: Run LBFGS benchmark
        run: |
          julia --project=benchmark -e '
            include("benchmark/benchmark-cutest-lbfgs.jl")
          '

      - name: Upload LBFGS benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: cutest-benchmark-stats-lbfgs-${{ matrix.split }}
          path: benchmark/result
          if-no-files-found: error


  Benchmark-Exact-Hessian:
    runs-on: windows-latest
    if: >
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'run CUTEst benchmark')
    env:
      MUMPS_SEQ: true
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'

      - name: Use Julia cache
        uses: julia-actions/cache@v2

      - name: Instantiate project
        run: |
          julia --project=benchmark -e '
            using Pkg
            Pkg.instantiate()
            mkpath("benchmark/result")
          '

      - name: Run benchmarks with exact Hessian
        run: |
          julia --project=benchmark -e '
            include("benchmark/benchmark-cutest-exact-hessian.jl")
          '

      - name: Upload exact-Hessian benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: cutest-benchmark-stats-exact-hessian
          path: benchmark/result
          if-no-files-found: error


  Compare-benchmarks:
    needs:
      - Benchmark-LBFGS
      - Benchmark-Exact-Hessian
    if: >
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'run CUTEst benchmark')
    uses: ./.github/workflows/CompareBenchmarks.yml